# Generated by Django 5.1.7 on 2025-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_text_alter_entry_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
